import { SQLFormatter } from '../src/formatter';
const f = new SQLFormatter();
const sql = `insert into dbo.Users (id,name,age) values (1,'John',30)`;
console.log('input:', sql);
let s = sql;
s = (f as any).normalizeClauses(s);
console.log('after normalizeClauses:', JSON.stringify(s));
s = (f as any).formatAllKeywords(s);
console.log('after formatAllKeywords:', JSON.stringify(s));
s = (f as any).formatStoredProcedureParameters(s);
console.log('after formatStoredProcedureParameters:', JSON.stringify(s));
s = (f as any).formatAllIdentifiers(s);
console.log('after formatAllIdentifiers:', JSON.stringify(s));
s = (f as any).addNoLock(s);
console.log('after addNoLock:', JSON.stringify(s));
s = (f as any).normalizeClauses(s);
console.log('after normalizeClauses2:', JSON.stringify(s));
s = (f as any).normalizeSpacing(s);
console.log('after normalizeSpacing:', JSON.stringify(s));
s = (f as any).cleanupAndIndent(s);
console.log('after cleanupAndIndent:', JSON.stringify(s));
s = (f as any).splitMergedClauses(s);
console.log('after splitMergedClauses:', JSON.stringify(s));
console.log('final trimmed:', JSON.stringify(s.trim()));
