import { SQLFormatter } from '../src/formatter';
const f = new SQLFormatter();
const s = `select departmentid, count(*) from dbo.Employees group by departmentid having count(*) > 5`;
console.log('input:', s);
let t = s;
console.log('after formatAllKeywords:', (f as any).formatAllKeywords(t));
let a = (f as any).formatAllKeywords(t);
let b = (f as any).formatStoredProcedureParameters(a);
console.log('after formatStoredProcedureParameters:', b);
let c = (f as any).formatAllIdentifiers(b);
console.log('after formatAllIdentifiers:', c);
let d = (f as any).addNoLock(c);
console.log('after addNoLock:', d);
let e = (f as any).normalizeClauses(d);
console.log('after normalizeClauses:', e);
let n = (f as any).normalizeSpacing(e);
console.log('after normalizeSpacing:', n);
let cl = (f as any).cleanupAndIndent(n);
console.log('after cleanupAndIndent:', cl);
let sm = (f as any).splitMergedClauses(cl);
console.log('after splitMergedClauses:', sm);
console.log('final formatted:', f.format(s));
